---
- hosts: kubernetes-master-nodes
  vars_files:
  - env_variables_ubuntu
  tasks:
  - name: Pulling images required for setting up a Kubernetes cluster
    shell: kubeadm config images pull

  - name: Initializing Kubernetes cluster
    shell: kubeadm init --ignore-preflight-errors=all --token-ttl=0
    register: output

  - name: Storing Logs and Generated token for future purpose.
    local_action: copy content={{ output.stdout }} dest={{ token_file }}

  - name: Copying required files
    shell: |
     mkdir -p $HOME/.kube
     sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
     sudo chown $(id -u):$(id -g) $HOME/.kube/config
  - name: Pause for cluster update
    pause:
      minutes: 1

  - name: Install Network Add-on
    shell: |
      kubectl apply -f https://github.com/weaveworks/weave/releases/download/v2.8.1/weave-daemonset-k8s.yaml
  - name: Configuring kubectl for "{{ ansible_user }}"
    shell: |
      echo "Hi whats this !!!"
      mkdir -p $HOME/.kube
      cp -rf /etc/kubernetes/admin.conf $HOME/
      chown $(id -u):$(id -g) $HOME/admin.conf
      echo "export KUBECONFIG=$HOME/admin.conf" >> ~/.bashrc
    tags: "t1"


