---
- hosts: all

  vars:
   packages:
   - containerd
   - kubeadm
   - kubectl
   - kubelet
   - docker-ce 
   - docker-ce-cli 
   - containerd.io 
   - docker-compose-plugin

  tasks:
  - name: reset the cluster
    command: kubeadm reset -f
    ignore_errors: true
  - name: Stop the deamons
    systemd:
      name: "{{item}}"
      state: stopped
    with_items:
      - docker
  - name: Removing Repo File of Kubernetes.
    file:
     path: /etc/yum.repos.d/kubernetes.repo
     state: absent

  - name: Uninstalling kubernetes related packages
    apt:
     name: "{{ item }}"
     state: absent
    with_items: "{{ packages }}"

  - name: Removing required files
    file:
     path: "{{ item }}"
     state: absent
    with_items:
    - /etc/kubernetes/
    - /var/lib/etcd/
    - $HOME/.kube/
    - /etc/apt/keyrings/docker.gpg
    - /etc/apt/sources.list.d/docker.list
    - /etc/containerd/config.toml 
    - /etc/apt/sources.list.d/kubernetes.list
    - /usr/share/keyrings/kubernetes-archive-keyring.gpg
    - /tmp/docker.gpg
    - /run/containerd/containerd.sock

  - name: Autoremove
    command: apt autoremove -y


  - name: Removing required files of "{{ ansible_user }}"
    shell: |
        rm -rf $HOME/admin.conf $HOME/.kube/
    become: yes
    become_user: "{{ ansible_user }}"    

